apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
#  type: NodePort
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
#      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-service
          image: anuragaggarwalnagarro01/api-service:0.0.1
          resources:
            requests:
              cpu: 50m
          env:
            - name: dbService
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: dbService
            - name: dbName
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: dbName
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 8082